INSERT INTO workers VALUES(null,0,'Samuel Rosa',041258);
INSERT INTO workers VALUES(null,1,'Paulo Coutos',045458);
INSERT INTO workers VALUES(null,3,'Renata Alemberg',065258);
INSERT INTO workers VALUES(null,4,'João Lira',041338);
INSERT INTO workers VALUES(null,0,'Natália Melo',041568);
INSERT INTO workers VALUES(null,2,'Fernanda Rosa',041458);
INSERT INTO workers VALUES(null,0,'Wagner Albuquerque',041988);
INSERT INTO workers VALUES(null,3,'Isabela Minnutti',041028);
INSERT INTO workers VALUES(null,4,'Joana Yoshino',041008);
INSERT INTO workers VALUES(null,0,'Mateus Pizzaiollo',041118);
INSERT INTO workers VALUES(null,3,'Frank Smith',041458);
INSERT INTO workers VALUES(null,0,'Paulo Guedes',041788);
INSERT INTO workers VALUES(null,2,'Maria Cepa',041988);
INSERT INTO workers VALUES(null,0,'Mateus Nashtergaellle',041778);
INSERT INTO workers VALUES(null,1,'Nielly Fiuza',041568);
INSERT INTO workers VALUES(null,1,'Brenda Ferraz',041338);
INSERT INTO workers VALUES(null,0,'William Bonner',041668);
INSERT INTO workers VALUES(null,0,'Fátima Bernardez',041998);
INSERT INTO workers VALUES(null,4,'Helena Bohan',041008);
INSERT INTO workers VALUES(null,0,'Suzana Gensai',041228);

INSERT INTO address VALUES(null,'São Paulo','SP','Brasil');
INSERT INTO address VALUES(null,'São Paulo','SP','Brasil');
INSERT INTO address VALUES(null,'Gramado','RS','Brasil');
INSERT INTO address VALUES(null,'Salvador','BA','Brasil');
INSERT INTO address VALUES(null,'São Paulo','SP','Brasil');
INSERT INTO address VALUES(null,'Amapá','AM','Brasil');
INSERT INTO address VALUES(null,'Campinas','SP','Brasil');
INSERT INTO address VALUES(null,'Macaé','RJ','Brasil');
INSERT INTO address VALUES(null,'Botafogo','RJ','Brasil');
INSERT INTO address VALUES(null,'San Francisco','CA','USA');
INSERT INTO address VALUES(null,'Manhattan','NY','USA');
INSERT INTO address VALUES(null,'Somões Filho','BA','Brasil');
INSERT INTO address VALUES(null,'Barueri','SP','Brasil');         
INSERT INTO address VALUES(null,'Manaus','AM','Brasil');
INSERT INTO address VALUES(null,'Curitiba','PA','Brasil');
INSERT INTO address VALUES(null,'Austin','Texas','USA');
INSERT INTO address VALUES(null,'São Paulo','SP','Brasil');
INSERT INTO address VALUES(null,'São José dos Campos','SP','Brasil');
INSERT INTO address VALUES(null,'Ouro Preto','MG','Brasil');
INSERT INTO address VALUES(null,'São Paulo','SP','Brasil');

INSERT INTO address_workers VALUES(1,1);
INSERT INTO address_workers VALUES(2,2);
INSERT INTO address_workers VALUES(3,3);
INSERT INTO address_workers VALUES(4,4);
INSERT INTO address_workers VALUES(5,5);
INSERT INTO address_workers VALUES(6,6);
INSERT INTO address_workers VALUES(7,7);
INSERT INTO address_workers VALUES(8,8);
INSERT INTO address_workers VALUES(9,9);
INSERT INTO address_workers VALUES(10,10);
INSERT INTO address_workers VALUES(11,11);
INSERT INTO address_workers VALUES(12,12);
INSERT INTO address_workers VALUES(13,13);
INSERT INTO address_workers VALUES(14,14);
INSERT INTO address_workers VALUES(15,15);
INSERT INTO address_workers VALUES(16,16);
INSERT INTO address_workers VALUES(17,17);
INSERT INTO address_workers VALUES(18,18);
INSERT INTO address_workers VALUES(19,19);
INSERT INTO address_workers VALUES(20,20);